import * as XLSX from 'xlsx';
import JSZip from 'jszip';
import { FIELD_TO_SQL } from './exporters';
import type { EntityRelation } from '../engine/relational-generator';

function columnDef(col: string, schema: Record<string, { type: string; size?: number }>) {
  const s = schema[col] || FIELD_TO_SQL[col];
  if (!s) return `"${col}" VARCHAR(255)`;
  const { type, size } = s;
  if (type === 'TEXT' || type === 'BOOLEAN' || type === 'DATE' || type === 'DATETIME' || type === 'UUID') {
    return `"${col}" ${type}`;
  }
  if (type === 'DECIMAL') {
    return `"${col}" DECIMAL(${size ?? 10}, 2)`;
  }
  if (size != null) {
    return `"${col}" ${type}(${size})`;
  }
  return `"${col}" ${type}`;
}

function escapeValue(v: unknown): string {
  if (v === null || v === undefined) return 'NULL';
  if (typeof v === 'number') return String(v);
  if (typeof v === 'boolean') return v ? 'TRUE' : 'FALSE';
  return "'" + String(v).replace(/'/g, "''") + "'";
}

function dataToCSV(data: Record<string, unknown>[]): string {
  if (data.length === 0) return '';
  const columns = Object.keys(data[0]);
  const header = columns.join(',');
  const rows = data.map(row =>
    columns.map(col => {
      const v = row[col];
      if (v === null || v === undefined) return '';
      const s = String(v);
      return s.includes(',') || s.includes('"') || s.includes('\n')
        ? '"' + s.replace(/"/g, '""') + '"'
        : s;
    }).join(',')
  );
  return header + '\n' + rows.join('\n');
}

export function toRelationalSQL(
  results: Map<string, Record<string, unknown>[]>,
  entityOrder: string[],
  relations: EntityRelation[],
  options?: { dropTables?: boolean }
): string {
  const lines: string[] = [];
  lines.push('-- Generated by Fake Database — Relational Mode');
  lines.push('');

  if (options?.dropTables) {
    for (const key of [...entityOrder].reverse()) {
      lines.push(`DROP TABLE IF EXISTS "${key}";`);
    }
    lines.push('');
  }

  for (const key of entityOrder) {
    const data = results.get(key) || [];
    if (data.length === 0) continue;
    const columns = Object.keys(data[0]);
    const colDefs = columns.map(col => '  ' + columnDef(col, {})).join(',\n');

    const fks = relations
      .filter(r => r.childKey === key)
      .map(r => `  FOREIGN KEY ("${r.childField}") REFERENCES "${r.parentKey}"("${r.parentField}")`)
      .join(',\n');

    const allDefs = fks ? colDefs + ',\n' + fks : colDefs;
    lines.push(`CREATE TABLE "${key}" (${allDefs});`);
    lines.push('');
  }

  for (const key of entityOrder) {
    const data = results.get(key) || [];
    if (data.length === 0) continue;
    const columns = Object.keys(data[0]);
    const cols = columns.map(c => `"${c}"`).join(', ');

    lines.push(`-- Data: ${key}`);
    lines.push(`INSERT INTO "${key}" (${cols}) VALUES`);

    const rows = data.map(row => {
      const values = columns.map(col => escapeValue(row[col])).join(', ');
      return `  (${values})`;
    });

    lines.push(rows.join(',\n') + ';');
    lines.push('');
  }

  return lines.join('\n');
}

export function toRelationalJSON(
  results: Map<string, Record<string, unknown>[]>,
  entityOrder: string[]
): string {
  const wrapper: Record<string, Record<string, unknown>[]> = {};
  for (const key of entityOrder) {
    wrapper[key] = results.get(key) || [];
  }
  return JSON.stringify(wrapper, null, 2);
}

export function toRelationalXLSX(
  results: Map<string, Record<string, unknown>[]>,
  entityOrder: string[]
): ArrayBuffer {
  const wb = XLSX.utils.book_new();
  for (const key of entityOrder) {
    const data = results.get(key) || [];
    if (data.length === 0) continue;
    const columns = Object.keys(data[0]);
    const ws = XLSX.utils.json_to_sheet(data, { header: columns });
    XLSX.utils.book_append_sheet(wb, ws, key);
  }
  return XLSX.write(wb, { type: 'array', bookType: 'xlsx' });
}

export async function toRelationalZIP(
  results: Map<string, Record<string, unknown>[]>,
  entityOrder: string[],
  relations: EntityRelation[]
): Promise<Blob> {
  const zip = new JSZip();

  for (const key of entityOrder) {
    const data = results.get(key) || [];
    if (data.length === 0) continue;
    zip.file(`${key}.csv`, dataToCSV(data));
  }

  const sql = toRelationalSQL(results, entityOrder, relations);
  zip.file('relational_data.sql', sql);

  const json = toRelationalJSON(results, entityOrder);
  zip.file('relational_data.json', json);

  const xlsxData = toRelationalXLSX(results, entityOrder);
  zip.file('relational_data.xlsx', xlsxData);

  return zip.generateAsync({ type: 'blob' });
}
